<?php

return [
    'name' => 'WaveCast Studio',
    'tagline' => 'Host, schedule, and broadcast story-rich podcasts from one cinematic channel.',
    'host' => 'Maya Rivers',
    'description' => 'A full-service podcast hub for interviews, live recordings, creator notes, and on-demand episode playback.',
    'email' => 'hello@wavecast.test',
    'live' => [
        'status' => 'Live every Wednesday at 8 PM ET',
        'title' => 'The Creator Roundtable',
        'description' => 'A live production room with audience questions, sponsor reads, chapter markers, and a post-show replay workflow.',
        'stream_url' => 'https://stream.wavecast.test/live',
        'next_show' => 'Wednesday, June 10 at 8:00 PM ET',
    ],
    'platforms' => [
        ['name' => 'Apple Podcasts', 'url' => 'https://podcasts.apple.com/'],
        ['name' => 'Spotify', 'url' => 'https://open.spotify.com/'],
        ['name' => 'RSS Feed', 'url' => '/podcast.xml'],
    ],
    'episodes' => [
        [
            'slug' => 'building-an-independent-audio-brand',
            'title' => 'Building an Independent Audio Brand',
            'number' => 42,
            'category' => 'Strategy',
            'duration' => '48 min',
            'published_at' => '2026-05-21',
            'guest' => 'Nora Bell',
            'summary' => 'How small teams plan seasons, package shows, and ship consistent podcast experiences without a traditional network.',
            'description' => 'Maya and Nora break down the operating rhythm behind a polished independent podcast: editorial calendars, launch checklists, audience promises, and the metrics that matter after release day.',
            'audio_url' => 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-1.mp3',
            'chapters' => ['Defining the audience promise', 'Season planning rituals', 'Packaging show notes', 'Launch-week measurement'],
        ],
        [
            'slug' => 'live-show-production-stack',
            'title' => 'The Live Show Production Stack',
            'number' => 41,
            'category' => 'Broadcasting',
            'duration' => '55 min',
            'published_at' => '2026-05-14',
            'guest' => 'Leo Chen',
            'summary' => 'A practical tour through rundown planning, remote guest prep, cue sheets, and redundant streaming paths for live podcast broadcasts.',
            'description' => 'This episode maps a resilient live podcast workflow, from backstage communication and audience moderation to stream backups and instant replay publishing.',
            'audio_url' => 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-2.mp3',
            'chapters' => ['Pre-show checks', 'Remote guest kits', 'Live audience flow', 'Replay publishing'],
        ],
        [
            'slug' => 'turning-listeners-into-members',
            'title' => 'Turning Listeners Into Members',
            'number' => 40,
            'category' => 'Growth',
            'duration' => '43 min',
            'published_at' => '2026-05-07',
            'guest' => 'Ari Patel',
            'summary' => 'Membership funnels, private feeds, bonus episodes, and retention rituals for audience-supported podcasts.',
            'description' => 'Ari shares how podcast teams can design membership tiers that feel generous, sustainable, and directly connected to the editorial mission.',
            'audio_url' => 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-3.mp3',
            'chapters' => ['Membership positioning', 'Private feed planning', 'Bonus content systems', 'Retention signals'],
        ],
    ],
];
